export interface Theme {
	id: string
	name: string
	description: string
	styles: {
		// Layout
		bodyBg: string
		bodyText: string
		// Header
		headerBg: string
		headerText: string
		headerBorder: string
		navLink: string
		navLinkHover: string
		contactButton: string
		contactButtonHover: string
		// Introduction
		introBg: string
		introText: string
		introBorder: string
		introNameColor: string
		introRoleColor: string
		// Experience
		experienceTitle: string
		experienceBorder: string
		experienceItemBg: string
		experienceItemBorder: string
		experienceItemHover: string
		experienceButton: string
		experienceButtonHover: string
		// Projects
		projectTitle: string
		projectCardBg: string
		projectCardBorder: string
		projectCardHover: string
		projectButton: string
		projectButtonHover: string
		// About
		aboutTitle: string
		aboutText: string
		aboutHighlight: string
		aboutImageBorder: string
		// Social Media
		socialButton: string
		socialButtonHover: string
		// Tags
		tagBg: string
		tagBorder: string
		tagText: string
		tagHover: string
		// Fonts
		fontFamily: string
		fontFamilyHeading: string
	}
}

export const themes: Theme[] = [
	{
		id: 'default',
		name: 'Original',
		description: 'Diseño original del portfolio',
		styles: {
			bodyBg: 'bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]',
			bodyText: '',
			headerBg: 'bg-sky-600',
			headerText: 'text-white',
			headerBorder: 'border-sky-700',
			navLink: '',
			navLinkHover: '',
			contactButton: '',
			contactButtonHover: '',
			introBg: 'bg-transparent',
			introText: '',
			introBorder: 'border-gray-200',
			introNameColor: '',
			introRoleColor: 'text-sky-600',
			experienceTitle: '',
			experienceBorder: 'border-gray-200',
			experienceItemBg: 'bg-transparent',
			experienceItemBorder: 'border-transparent',
			experienceItemHover: 'hover:border-gray-300',
			experienceButton: 'bg-sky-600 text-white',
			experienceButtonHover: 'hover:bg-sky-700',
			projectTitle: '',
			projectCardBg: 'bg-transparent',
			projectCardBorder: 'border-transparent',
			projectCardHover: 'hover:shadow-lg',
			projectButton: 'bg-gray-600 text-white',
			projectButtonHover: 'hover:bg-gray-700',
			aboutTitle: '',
			aboutText: '',
			aboutHighlight: 'text-sky-600',
			aboutImageBorder: 'border-gray-300',
			socialButton: 'bg-gray-600 border-gray-600 text-white',
			socialButtonHover: 'hover:bg-gray-700',
			tagBg: 'bg-gray-900',
			tagBorder: 'border-gray-800',
			tagText: 'text-white',
			tagHover: 'hover:bg-gray-800',
			fontFamily: "'Onest Variable', sans-serif",
			fontFamilyHeading: "'Onest Variable', sans-serif",
		},
	},
	{
		id: 'modern-minimalist',
		name: 'Modern Minimalist',
		description: 'Diseño minimalista y limpio con mucho espacio en blanco',
		styles: {
			bodyBg: 'bg-white',
			bodyText: 'text-black',
			headerBg: 'bg-white/80 backdrop-blur-sm',
			headerText: 'text-black',
			headerBorder: 'border-none',
			navLink: 'text-gray-600 hover:text-black',
			navLinkHover: 'hover:text-black',
			contactButton: 'bg-black text-white hover:bg-gray-800 rounded-full shadow-md hover:shadow-lg',
			contactButtonHover: 'hover:bg-gray-800 hover:shadow-lg',
			introBg: 'bg-white',
			introText: 'text-gray-700',
			introBorder: 'border-none',
			introNameColor: 'text-black font-light',
			introRoleColor: 'text-gray-600',
			experienceTitle: 'text-black font-light tracking-tight',
			experienceBorder: 'border-gray-300',
			experienceItemBg: 'bg-white',
			experienceItemBorder: 'border-gray-200',
			experienceItemHover: 'hover:shadow-lg',
			experienceButton: 'bg-black text-white px-8 py-3 rounded-full hover:bg-gray-800 shadow-md hover:shadow-lg',
			experienceButtonHover: 'hover:bg-gray-800 hover:shadow-lg',
			projectTitle: 'text-black font-light tracking-tight',
			projectCardBg: 'bg-white',
			projectCardBorder: 'border-2 border-gray-200',
			projectCardHover: 'hover:shadow-xl',
			projectButton: 'bg-black text-white px-8 py-3 rounded-full hover:bg-gray-800 shadow-md hover:shadow-lg',
			projectButtonHover: 'hover:bg-gray-800 hover:shadow-lg',
			aboutTitle: 'text-black font-light tracking-tight',
			aboutText: 'text-gray-700',
			aboutHighlight: 'text-black font-semibold',
			aboutImageBorder: 'border-2 border-gray-200',
			socialButton: 'bg-white text-black border-2 border-gray-200 rounded-full hover:border-black hover:shadow-md',
			socialButtonHover: 'hover:border-black hover:shadow-md',
			tagBg: 'bg-gray-900',
			tagBorder: 'border-gray-300',
			tagText: 'text-white',
			tagHover: 'hover:border-black',
			fontFamily: "'Onest Variable', sans-serif",
			fontFamilyHeading: "'Onest Variable', sans-serif",
		},
	},
	{
		id: 'dark-neon',
		name: 'Dark Neon',
		description: 'Estilo cyberpunk con efectos neon y fondo oscuro',
		styles: {
			bodyBg: 'bg-gray-900',
			bodyText: 'text-gray-100',
			headerBg: 'bg-gray-900/90 backdrop-blur-sm',
			headerText: 'text-cyan-400',
			headerBorder: 'border-cyan-500/30',
			navLink: 'text-cyan-400 hover:text-cyan-300 drop-shadow-[0_0_10px_rgba(6,182,212,0.5)]',
			navLinkHover: 'hover:text-cyan-300',
			contactButton: 'bg-gradient-to-r from-cyan-500 to-blue-600 text-gray-900 hover:from-cyan-400 hover:to-blue-500 shadow-[0_0_20px_rgba(6,182,212,0.6)] hover:shadow-[0_0_30px_rgba(6,182,212,0.8)]',
			contactButtonHover: 'hover:from-cyan-400 hover:to-blue-500 hover:shadow-[0_0_30px_rgba(6,182,212,0.8)]',
			introBg: 'bg-gray-800/50 backdrop-blur-sm',
			introText: 'text-gray-100',
			introBorder: 'border-cyan-500/50',
			introNameColor: 'text-cyan-400 drop-shadow-[0_0_15px_rgba(6,182,212,0.8)]',
			introRoleColor: 'text-blue-400',
			experienceTitle: 'text-cyan-400 drop-shadow-[0_0_15px_rgba(6,182,212,0.8)]',
			experienceBorder: 'border-cyan-500/30',
			experienceItemBg: 'bg-gray-800/50',
			experienceItemBorder: 'border-cyan-500/30',
			experienceItemHover: 'hover:border-cyan-400 hover:shadow-[0_0_20px_rgba(6,182,212,0.4)]',
			experienceButton: 'bg-gradient-to-r from-cyan-500 to-blue-600 text-gray-900 hover:from-cyan-400 hover:to-blue-500 shadow-[0_0_20px_rgba(6,182,212,0.6)] hover:shadow-[0_0_30px_rgba(6,182,212,0.8)] hover:scale-105',
			experienceButtonHover: 'hover:from-cyan-400 hover:to-blue-500 hover:shadow-[0_0_30px_rgba(6,182,212,0.8)] hover:scale-105',
			projectTitle: 'text-cyan-400 drop-shadow-[0_0_15px_rgba(6,182,212,0.8)]',
			projectCardBg: 'bg-gray-800/50',
			projectCardBorder: 'border-2 border-cyan-500/30',
			projectCardHover: 'hover:border-cyan-400 hover:shadow-[0_0_30px_rgba(6,182,212,0.4)]',
			projectButton: 'bg-gradient-to-r from-cyan-500 to-blue-600 text-gray-900 hover:from-cyan-400 hover:to-blue-500 shadow-[0_0_20px_rgba(6,182,212,0.6)] hover:shadow-[0_0_30px_rgba(6,182,212,0.8)] hover:scale-105',
			projectButtonHover: 'hover:from-cyan-400 hover:to-blue-500 hover:shadow-[0_0_30px_rgba(6,182,212,0.8)] hover:scale-105',
			aboutTitle: 'text-cyan-400 drop-shadow-[0_0_15px_rgba(6,182,212,0.8)]',
			aboutText: 'text-gray-300',
			aboutHighlight: 'text-cyan-400 font-bold',
			aboutImageBorder: 'border-2 border-cyan-500',
			socialButton: 'bg-gray-900 text-cyan-400 border-2 border-cyan-500/50 hover:border-cyan-400 hover:shadow-[0_0_15px_rgba(6,182,212,0.6)]',
			socialButtonHover: 'hover:border-cyan-400 hover:shadow-[0_0_15px_rgba(6,182,212,0.6)]',
			tagBg: 'bg-gray-800/80',
			tagBorder: 'border-cyan-500/50',
			tagText: 'text-cyan-400',
			tagHover: 'hover:border-cyan-400 hover:shadow-[0_0_10px_rgba(6,182,212,0.5)]',
			fontFamily: "'Onest Variable', sans-serif",
			fontFamilyHeading: "'Onest Variable', sans-serif",
		},
	},
	{
		id: 'gradient-glassmorphism',
		name: 'Gradient Glassmorphism',
		description: 'Gradientes coloridos con efectos de vidrio esmerilado',
		styles: {
			bodyBg: 'bg-gradient-to-br from-purple-500 via-pink-500 to-orange-400',
			bodyText: 'text-white',
			headerBg: 'bg-white/10 backdrop-blur-lg',
			headerText: 'text-white',
			headerBorder: 'border-white/20',
			navLink: 'text-white/90 hover:text-white drop-shadow-lg',
			navLinkHover: 'hover:text-white',
			contactButton: 'bg-white/20 backdrop-blur-lg border-2 border-white/30 text-white hover:bg-white/30 hover:border-white/50 shadow-xl',
			contactButtonHover: 'hover:bg-white/30 hover:border-white/50',
			introBg: 'bg-white/10 backdrop-blur-lg',
			introText: 'text-white',
			introBorder: 'border-white/20',
			introNameColor: 'text-white drop-shadow-lg',
			introRoleColor: 'text-white/90',
			experienceTitle: 'bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent',
			experienceBorder: 'border-purple-300/50',
			experienceItemBg: 'bg-white/10 backdrop-blur-lg',
			experienceItemBorder: 'border-white/20',
			experienceItemHover: 'hover:bg-white/20 hover:border-purple-400/50',
			experienceButton: 'bg-gradient-to-r from-purple-500 to-pink-500 text-white hover:from-purple-600 hover:to-pink-600 shadow-xl hover:shadow-2xl hover:scale-105',
			experienceButtonHover: 'hover:from-purple-600 hover:to-pink-600 hover:shadow-2xl hover:scale-105',
			projectTitle: 'bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent',
			projectCardBg: 'bg-white/10 backdrop-blur-lg',
			projectCardBorder: 'border-2 border-white/20',
			projectCardHover: 'hover:bg-white/20 hover:border-purple-400/50 hover:scale-105',
			projectButton: 'bg-gradient-to-r from-purple-500 to-pink-500 text-white hover:from-purple-600 hover:to-pink-600 shadow-xl hover:shadow-2xl hover:scale-105',
			projectButtonHover: 'hover:from-purple-600 hover:to-pink-600 hover:shadow-2xl hover:scale-105',
			aboutTitle: 'bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent',
			aboutText: 'text-white/90',
			aboutHighlight: 'text-white font-bold',
			aboutImageBorder: 'border-4 border-white/30',
			socialButton: 'bg-purple-900/40 backdrop-blur-lg text-white border-2 border-purple-400/40 hover:bg-purple-800/50 hover:border-purple-400/70 shadow-lg hover:shadow-purple-500/50',
			socialButtonHover: 'hover:bg-purple-800/50 hover:border-purple-400/70 hover:shadow-purple-500/50',
			tagBg: 'bg-purple-600/20',
			tagBorder: 'border-purple-500/40',
			tagText: 'text-white',
			tagHover: 'hover:border-purple-400',
			fontFamily: "'Onest Variable', sans-serif",
			fontFamilyHeading: "'Onest Variable', sans-serif",
		},
	},
	{
		id: 'code-editor',
		name: 'Code Editor',
		description: 'Inspirado en VS Code con sintaxis highlighting',
		styles: {
			bodyBg: 'bg-[#1e1e1e]',
			bodyText: 'text-[#d4d4d4]',
			headerBg: 'bg-[#252526]',
			headerText: 'text-[#d4d4d4]',
			headerBorder: 'border-[#2d2d30]',
			navLink: 'text-[#9cdcfe] hover:text-[#4fc1ff]',
			navLinkHover: 'hover:text-[#4fc1ff]',
			contactButton: 'bg-[#0e639c] text-white hover:bg-[#1177bb] border-none',
			contactButtonHover: 'hover:bg-[#1177bb]',
			introBg: 'bg-[#1e1e1e]',
			introText: 'text-[#d4d4d4]',
			introBorder: 'border-[#2d2d30]',
			introNameColor: 'text-[#9cdcfe]',
			introRoleColor: 'text-[#4ec9b0]',
			experienceTitle: 'text-[#dcdcaa]',
			experienceBorder: 'border-[#007acc]/50',
			experienceItemBg: 'bg-[#252526]',
			experienceItemBorder: 'border-[#2d2d30]',
			experienceItemHover: 'hover:border-[#007acc]',
			experienceButton: 'bg-[#0e639c] text-white hover:bg-[#1177bb] border-none',
			experienceButtonHover: 'hover:bg-[#1177bb]',
			projectTitle: 'text-[#9cdcfe]',
			projectCardBg: 'bg-[#252526]',
			projectCardBorder: 'border-2 border-[#2d2d30]',
			projectCardHover: 'hover:border-[#007acc]',
			projectButton: 'bg-[#0e639c] text-white hover:bg-[#1177bb] border-none',
			projectButtonHover: 'hover:bg-[#1177bb]',
			aboutTitle: 'text-[#4ec9b0]',
			aboutText: 'text-[#d4d4d4]',
			aboutHighlight: 'text-[#4ec9b0] font-bold',
			aboutImageBorder: 'border-2 border-[#007acc]',
			socialButton: 'bg-[#0e639c] text-white border border-[#007acc] hover:bg-[#1177bb]',
			socialButtonHover: 'hover:bg-[#1177bb]',
			tagBg: 'bg-[#252526]',
			tagBorder: 'border-[#2d2d30]',
			tagText: 'text-[#9cdcfe]',
			tagHover: 'hover:border-[#007acc]',
			fontFamily: "'Fira Code', monospace",
			fontFamilyHeading: "'Fira Code', monospace",
		},
	},
	{
		id: 'holographic-tech',
		name: 'Holographic Tech',
		description: 'Efectos holográficos futuristas con gradientes iridiscentes',
		styles: {
			bodyBg: 'bg-gradient-to-br from-slate-950 via-purple-950 to-slate-950',
			bodyText: 'text-gray-100',
			headerBg: 'bg-slate-900/40 backdrop-blur-xl',
			headerText: 'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400',
			headerBorder: 'border-purple-500/30',
			navLink: 'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-400 hover:from-cyan-300 hover:to-purple-300',
			navLinkHover: 'hover:from-cyan-300 hover:to-purple-300',
			contactButton: 'text-black bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 hover:from-cyan-300 hover:via-purple-300 hover:to-pink-300 shadow-[0_0_20px_rgba(168,85,247,0.6)] hover:shadow-[0_0_30px_rgba(168,85,247,0.8)]',
			contactButtonHover: 'hover:from-cyan-300 hover:via-purple-300 hover:to-pink-300 hover:shadow-[0_0_30px_rgba(168,85,247,0.8)]',
			introBg: 'bg-gradient-to-br from-purple-900/20 via-indigo-900/20 to-purple-900/20 backdrop-blur-xl',
			introText: 'text-gray-100',
			introBorder: 'border-2 border-purple-500/30',
			introNameColor: 'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 drop-shadow-[0_0_20px_rgba(168,85,247,0.6)]',
			introRoleColor: 'text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400',
			experienceTitle: 'text-transparent bg-clip-text bg-gradient-to-r from-pink-400 via-purple-400 to-cyan-400 drop-shadow-[0_0_20px_rgba(168,85,247,0.6)]',
			experienceBorder: 'border-purple-500/30',
			experienceItemBg: 'bg-gradient-to-br from-purple-900/20 via-indigo-900/20 to-purple-900/20 backdrop-blur-xl',
			experienceItemBorder: 'border-2 border-purple-500/30',
			experienceItemHover: 'hover:border-purple-400/60 hover:shadow-[0_0_30px_rgba(168,85,247,0.4)]',
			experienceButton: 'text-black bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 hover:from-cyan-300 hover:via-purple-300 hover:to-pink-300 shadow-[0_0_20px_rgba(168,85,247,0.6)] hover:shadow-[0_0_30px_rgba(168,85,247,0.8)]',
			experienceButtonHover: 'hover:from-cyan-300 hover:via-purple-300 hover:to-pink-300 hover:shadow-[0_0_30px_rgba(168,85,247,0.8)]',
			projectTitle: 'text-transparent bg-clip-text bg-gradient-to-r from-pink-400 via-purple-400 to-cyan-400 drop-shadow-[0_0_20px_rgba(168,85,247,0.6)]',
			projectCardBg: 'bg-gradient-to-br from-purple-900/20 via-indigo-900/20 to-purple-900/20 backdrop-blur-xl',
			projectCardBorder: 'border-2 border-purple-500/30',
			projectCardHover: 'hover:border-purple-400/60 hover:shadow-[0_0_50px_rgba(168,85,247,0.5)] hover:scale-105',
			projectButton: 'text-black bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 hover:from-cyan-300 hover:via-purple-300 hover:to-pink-300 shadow-[0_0_20px_rgba(168,85,247,0.6)] hover:shadow-[0_0_30px_rgba(168,85,247,0.8)]',
			projectButtonHover: 'hover:from-cyan-300 hover:via-purple-300 hover:to-pink-300 hover:shadow-[0_0_30px_rgba(168,85,247,0.8)]',
			aboutTitle: 'text-transparent bg-clip-text bg-gradient-to-r from-pink-400 via-purple-400 to-cyan-400 drop-shadow-[0_0_20px_rgba(168,85,247,0.6)]',
			aboutText: 'text-gray-300',
			aboutHighlight: 'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-400 font-bold',
			aboutImageBorder: 'border-2 border-purple-500',
			socialButton: 'bg-purple-900/40 backdrop-blur-lg border-2 border-purple-500/50 text-white hover:bg-purple-800/50 hover:border-purple-400 hover:shadow-[0_0_15px_rgba(168,85,247,0.6)]',
			socialButtonHover: 'hover:bg-purple-800/50 hover:border-purple-400 hover:shadow-[0_0_15px_rgba(168,85,247,0.6)]',
			tagBg: 'bg-purple-600/20',
			tagBorder: 'border-purple-500/40',
			tagText: 'text-white',
			tagHover: 'hover:border-purple-400 hover:shadow-[0_0_10px_rgba(168,85,247,0.5)]',
			fontFamily: "'Orbitron', sans-serif",
			fontFamilyHeading: "'Rajdhani', sans-serif",
		},
	},
	{
		id: 'terminal-matrix',
		name: 'Terminal Matrix',
		description: 'Estilo terminal de comandos con tema Matrix verde sobre negro',
		styles: {
			bodyBg: 'bg-black',
			bodyText: 'text-green-400',
			headerBg: 'bg-black',
			headerText: 'text-green-400',
			headerBorder: 'border-green-500/30',
			navLink: 'text-green-400 hover:text-green-300 font-mono',
			navLinkHover: 'hover:text-green-300',
			contactButton: 'bg-green-500/20 text-green-400 border-2 border-green-500 hover:bg-green-500/30 hover:border-green-400',
			contactButtonHover: 'hover:bg-green-500/30 hover:border-green-400',
			introBg: 'bg-black/90',
			introText: 'text-green-400',
			introBorder: 'border-green-500/50',
			introNameColor: 'text-green-400 font-mono',
			introRoleColor: 'text-green-300',
			experienceTitle: 'text-green-400 font-mono',
			experienceBorder: 'border-green-500/30',
			experienceItemBg: 'bg-black/50',
			experienceItemBorder: 'border-green-500/30',
			experienceItemHover: 'hover:border-green-400 hover:bg-green-500/10',
			experienceButton: 'bg-green-500/20 text-green-400 border-2 border-green-500 hover:bg-green-500/30 hover:border-green-400',
			experienceButtonHover: 'hover:bg-green-500/30 hover:border-green-400',
			projectTitle: 'text-green-400 font-mono',
			projectCardBg: 'bg-black/50',
			projectCardBorder: 'border-2 border-green-500/30',
			projectCardHover: 'hover:border-green-400 hover:bg-green-500/10',
			projectButton: 'bg-green-500/20 text-green-400 border-2 border-green-500 hover:bg-green-500/30 hover:border-green-400',
			projectButtonHover: 'hover:bg-green-500/30 hover:border-green-400',
			aboutTitle: 'text-green-400 font-mono',
			aboutText: 'text-green-300',
			aboutHighlight: 'text-green-400 font-bold',
			aboutImageBorder: 'border-2 border-green-500',
			socialButton: 'bg-green-500/20 text-green-400 border-2 border-green-500 hover:bg-green-500/30 hover:border-green-400',
			socialButtonHover: 'hover:bg-green-500/30 hover:border-green-400',
			tagBg: 'bg-green-900/30',
			tagBorder: 'border-green-500/50',
			tagText: 'text-green-400',
			tagHover: 'hover:border-green-400 hover:bg-green-500/20',
			fontFamily: "'IBM Plex Mono', monospace",
			fontFamilyHeading: "'IBM Plex Mono', monospace",
		},
	},
	{
		id: 'blueprint-tech',
		name: 'Blueprint Tech',
		description: 'Estilo de planos técnicos con líneas y medidas',
		styles: {
			bodyBg: 'bg-blue-950',
			bodyText: 'text-blue-100',
			headerBg: 'bg-blue-900/50',
			headerText: 'text-blue-200',
			headerBorder: 'border-blue-400/30',
			navLink: 'text-blue-200 hover:text-blue-100 font-mono',
			navLinkHover: 'hover:text-blue-100',
			contactButton: 'bg-blue-500/20 text-blue-200 border-2 border-blue-400 hover:bg-blue-500/30 hover:border-blue-300',
			contactButtonHover: 'hover:bg-blue-500/30 hover:border-blue-300',
			introBg: 'bg-blue-900/30',
			introText: 'text-blue-100',
			introBorder: 'border-blue-400/50',
			introNameColor: 'text-blue-200 font-mono',
			introRoleColor: 'text-blue-300',
			experienceTitle: 'text-blue-200 font-mono',
			experienceBorder: 'border-blue-400/30',
			experienceItemBg: 'bg-blue-900/30',
			experienceItemBorder: 'border-blue-400/30',
			experienceItemHover: 'hover:border-blue-300 hover:bg-blue-800/30',
			experienceButton: 'bg-blue-500/20 text-blue-200 border-2 border-blue-400 hover:bg-blue-500/30 hover:border-blue-300',
			experienceButtonHover: 'hover:bg-blue-500/30 hover:border-blue-300',
			projectTitle: 'text-blue-200 font-mono',
			projectCardBg: 'bg-blue-900/30',
			projectCardBorder: 'border-2 border-blue-400/30',
			projectCardHover: 'hover:border-blue-300 hover:bg-blue-800/30',
			projectButton: 'bg-blue-500/20 text-blue-200 border-2 border-blue-400 hover:bg-blue-500/30 hover:border-blue-300',
			projectButtonHover: 'hover:bg-blue-500/30 hover:border-blue-300',
			aboutTitle: 'text-blue-200 font-mono',
			aboutText: 'text-blue-100',
			aboutHighlight: 'text-blue-200 font-bold',
			aboutImageBorder: 'border-2 border-blue-400',
			socialButton: 'bg-blue-500/20 text-blue-200 border-2 border-blue-400 hover:bg-blue-500/30 hover:border-blue-300',
			socialButtonHover: 'hover:bg-blue-500/30 hover:border-blue-300',
			tagBg: 'bg-blue-800/30',
			tagBorder: 'border-blue-400/50',
			tagText: 'text-blue-200',
			tagHover: 'hover:border-blue-300 hover:bg-blue-700/30',
			fontFamily: "'Roboto Mono', monospace",
			fontFamilyHeading: "'Chakra Petch', sans-serif",
		},
	},
]

export const getThemeById = (id: string): Theme | undefined => {
	return themes.find((theme) => theme.id === id)
}

export const DEFAULT_THEME_ID = 'default'
